services:
  - type: web
    name: gomotor-backend
    env: node
    buildCommand: |
      npm ci
      npx puppeteer browsers install chrome
      npm run build
    startCommand: npm run serve
    envVars:
      - key: NODE_ENV
        value: production
      - key: CHROME_EXECUTABLE_PATH
        value: /opt/render/.cache/puppeteer/chrome/linux-*/chrome-linux64/chrome
    disk:
      name: puppeteer-cache
      mountPath: /opt/render/.cache
      sizeGB: 1
