services:
  - type: web
    name: gomotor-backend
    env: node
    buildCommand: |
      npm ci
      npx puppeteer browsers install chrome
      npm run build
    startCommand: npm run serve
    envVars:
      - key: NODE_ENV
        value: production
